import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "com-dirusoft",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <div className="dark" />
      <body className="relative h-full w-full bg-neutral-950">
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">Dirusoft</Link>
        </header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} com-dirusoft
        </footer>
      </body>
    </html>
  );
}
